name: CI Support

on:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "**.cpp"
      - "**.hpp"
      - "**.py"
      - "**.pyx"  # Added for Cython files
      - "**.build"

permissions:
  contents: read

jobs:
  help_command:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          python -m pip install meson==1.0.0 ninja==1.11.1 cython==3.0.8
    - name: Setup Build Directory
      run: |
          meson setup builddir -Dwith_test=enabled
    - name: Compile Source Code
      run: |
          meson compile -C builddir
    - name: Test Project Code
      run: |
          meson test -C builddir -v --test-args='--help'

  version_command:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          python -m pip install meson==1.0.0 ninja==1.11.1 cython==3.0.8
    - name: Setup Build Directory
      run: |
          meson setup builddir -Dwith_test=enabled
    - name: Compile Source Code
      run: |
          meson compile -C builddir
    - name: Test Project Code
      run: |
          meson test -C builddir -v --test-args='--version'

  tip_command:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          python -m pip install meson==1.0.0 ninja==1.11.1 cython==3.0.8
    - name: Setup Build Directory
      run: |
          meson setup builddir -Dwith_test=enabled
    - name: Compile Source Code
      run: |
          meson compile -C builddir
    - name: Test Project Code
      run: |
          meson test -C builddir -v --test-args='--tip'

  color_command:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          python -m pip install meson==1.0.0 ninja==1.11.1 cython==3.0.8
    - name: Setup Build Directory
      run: |
          meson setup builddir -Dwith_test=enabled
    - name: Compile Source Code
      run: |
          meson compile -C builddir
    - name: Test Project Code
      run: |
          meson test -C builddir -v --test-args='--color'

  command_verbose:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          python -m pip install meson==1.0.0 ninja==1.11.1 cython==3.0.8
    - name: Setup Build Directory
      run: |
          meson setup builddir -Dwith_test=enabled
    - name: Compile Source Code
      run: |
          meson compile -C builddir
    - name: Test Project Code
      run: |
          meson test -C builddir -v --test-args='--verbose'

  command_cutback:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          python -m pip install meson==1.0.0 ninja==1.11.1 cython==3.0.8
    - name: Setup Build Directory
      run: |
          meson setup builddir -Dwith_test=enabled
    - name: Compile Source Code
      run: |
          meson compile -C builddir
    - name: Test Project Code
      run: |
          meson test -C builddir -v --test-args='--cutback'

  command_debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          python -m pip install meson==1.0.0 ninja==1.11.1 cython==3.0.8
    - name: Setup Build Directory
      run: |
          meson setup builddir -Dwith_test=enabled
    - name: Compile Source Code
      run: |
          meson compile -C builddir
    - name: Test Project Code
      run: |
          meson test -C builddir -v --test-args='--debug'

  command_repeat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          python -m pip install meson==1.0.0 ninja==1.11.1 cython==3.0.8
    - name: Setup Build Directory
      run: |
          meson setup builddir -Dwith_test=enabled
    - name: Compile Source Code
      run: |
          meson compile -C builddir
    - name: Test Project Code
      run: |
          meson test -C builddir -v --test-args='--reapat 10'
        