#
# under: devops:
# author: Michael Gene Brockus (Dreamer)
# gmail: <michaelbrockus@gmail.com>
#
name: Host System CI

#
# We have is configured so that ci_runner_linux only runs
# when source files, build scripts and this CI files is
# changed, we should not just run CI for all changes.
#
on:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "**.txt"
      - "**.build"
  pull_request:
    branches:
      - "main"
      - "next"
    paths:
      - "**.c"
      - "**.h"
      - "**.txt"
      - "**.build"

permissions:
  contents: read

#
# Full-on DevOps pipline for testing on mock host systems
# from Windwos, Max OS, and Linux systems.
# 
jobs:
  #
  # Mac OSX latest host system target
  #
  host_macosx_latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build System
      run: |
          pip install meson==1.0.0 ninja==1.11.1 scan-build
          brew install cppcheck
    - name: Setup Build Directory
      run: |
            scan-build meson setup builddir -Dwith_tests=enabled
    - name: Scan Compile Commands
      run: |
            cppcheck --project=builddir/compile_commands.json
    - name: Compile Source Code
      run: |
            scan-build meson compile -C builddir -v
    - name: Test Project Code
      run: |
            scan-build meson test -C builddir -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: MacOSX_latest_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  #
  # Mac OSX 11 host system target
  #
  host_macosx_11:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build System
      run: |
          pip install meson==1.0.0 ninja==1.11.1 scan-build
          brew install cppcheck
    - name: Setup Build Directory
      run: |
            scan-build meson setup builddir -Dwith_tests=enabled
    - name: Scan Compile Commands
      run: |
            cppcheck --project=builddir/compile_commands.json
    - name: Compile Source Code
      run: |
            scan-build meson compile -C builddir -v
    - name: Test Project Code
      run: |
            scan-build meson test -C builddir -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: MacOSX_11_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  #
  # Mac OSX 12 host system target
  #
  host_macosx_12:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build System
      run: |
          pip install meson==1.0.0 ninja==1.11.1 scan-build
          brew install cppcheck
    - name: Setup Build Directory
      run: |
            scan-build meson setup builddir -Dwith_tests=enabled
    - name: Scan Compile Commands
      run: |
            cppcheck --project=builddir/compile_commands.json
    - name: Compile Source Code
      run: |
            scan-build meson compile -C builddir -v
    - name: Test Project Code
      run: |
            scan-build meson test -C builddir -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: MacOSX_12_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  #
  # Mac OSX 12 host system target
  #
  host_macosx_13:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build System
      run: |
          pip install meson==1.0.0 ninja==1.11.1 scan-build
          brew install cppcheck
    - name: Setup Build Directory
      run: |
           scan-build meson setup builddir -Dwith_tests=enabled
    - name: Scan Compile Commands
      run: |
           cppcheck --project=builddir/compile_commands.json
    - name: Compile Source Code
      run: |
           scan-build meson compile -C builddir -v
    - name: Test Project Code
      run: |
           scan-build meson test -C builddir -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: MacOSX_13_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  #
  # Windows latest host system target
  #
  host_windows_latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build System
      run: |
          pip install meson==1.0.0 ninja==1.11.1
    - name: Setup Build Directory
      run: |
            meson setup builddir -Dwith_tests=enabled
    - name: Compile Source Code
      run: |
            meson compile -C builddir -v
    - name: Test Project Code
      run: |
            meson test -C builddir -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Windows_latest_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  #
  # Windows 2022 host system target
  #
  host_windows_2022:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build System
      run: |
          pip install meson==1.0.0 ninja==1.11.1
    - name: Setup Build Directory
      run: |
            meson setup builddir -Dwith_tests=enabled
    - name: Compile Source Code
      run: |
            meson compile -C builddir -v
    - name: Test Project Code
      run: |
            meson test -C builddir -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Windows_2022_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  #
  # Windows MinGW32 host system target
  #
  host_windows_mingw32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Setup MinGW 32
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw32
        update: true
    - name: Install Meson Build System
      run: |
          pip install meson==1.0.0 ninja==1.11.1
    - name: Setup Build Directory
      run: |
            meson setup builddir -Dwith_tests=enabled
    - name: Compile Source Code
      run: |
            meson compile -C builddir -v
    - name: Test Project Code
      run: |
            meson test -C builddir -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: mingw32_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  #
  # Windows MinGW64 host system target
  #
  host_windows_mingw64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Setup MinGW 64
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
    - name: Install Meson Build System
      run: |
          pip install meson==1.0.0 ninja==1.11.1
    - name: Setup Build Directory
      run: |
            meson setup builddir -Dwith_tests=enabled
    - name: Compile Source Code
      run: |
            meson compile -C builddir -v
    - name: Test Project Code
      run: |
            meson test -C builddir -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: MinGW64_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  #
  # Windows MSYS host system target
  #
  host_windows_msys:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Setup MSYS
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
    - name: Install Meson Build System
      run: |
          pip install meson==1.0.0 ninja==1.11.1
    - name: Setup Build Directory
      run: |
           meson setup builddir -Dwith_tests=enabled
    - name: Compile Source Code
      run: |
           meson compile -C builddir -v
    - name: Test Project Code
      run: |
           meson test -C builddir -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: MSYS_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  #
  # Ubuntu host latest host system target
  #
  host_ubuntu_latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build System
      run: |
          pip install meson==1.0.0 ninja==1.11.1 scan-build
          sudo apt-get install -y cppcheck gcc
    - name: Setup Build Directory
      run: |
            scan-build meson setup builddir -Dwith_tests=enabled
    - name: Scan Compile Commands
      run: |
            cppcheck --project=builddir/compile_commands.json
    - name: Compile Source Code
      run: |
            scan-build meson compile -C builddir
    - name: Test Project Code
      run: |
            scan-build meson test -C builddir -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Ubuntu_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  #
  # Ubuntu host 22.04 host system target
  #
  host_ubuntu_22_04:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build System
      run: |
          pip install meson==1.0.0 ninja==1.11.1 scan-build
          sudo apt-get install -y cppcheck gcc
    - name: Setup Build Directory
      run: |
            scan-build meson setup builddir -Dwith_tests=enabled
    - name: Scan Compile Commands
      run: |
            cppcheck --project=builddir/compile_commands.json
    - name: Compile Source Code
      run: |
            scan-build meson compile -C builddir
    - name: Test Project Code
      run: |
            scan-build meson test -C builddir -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Ubuntu_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  #
  # Ubuntu host 20.04 host system target
  #
  host_ubuntu_20_04:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build System
      run: |
          pip install meson==1.0.0 ninja==1.11.1 scan-build
          sudo apt-get install -y cppcheck gcc
    - name: Setup Build Directory
      run: |
           scan-build meson setup builddir -Dwith_tests=enabled
    - name: Scan Compile Commands
      run: |
           cppcheck --project=builddir/compile_commands.json
    - name: Compile Source Code
      run: |
           scan-build meson compile -C builddir
    - name: Test Project Code
      run: |
           scan-build meson test -C builddir -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Ubuntu_Meson_Testlog
        path: builddir/meson-logs/testlog.txt