#
# under: devops:
# author: Michael Gene Brockus (Dreamer)
# gmail: <michaelbrockus@gmail.com>
#
name: Samples CI

on:
  push:
    paths:
      - "**.txt"
      - "**.c"
      - "**.cpp"
      - "**.rs"
      - "**.d"
      - "**.build"
  pull_request:
    branches:
      - "main"
    paths:
      - "**.txt"
      - "**.c"
      - "**.cpp"
      - "**.rs"
      - "**.d"
      - "**.build"

jobs:
  run_samples_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build System
      run: |
          pip install meson ninja
          sudo apt-get install -y gcc
    - name: Setup Build Directory
      run: |
            meson setup builddir -Dwith_demo=enabled
    - name: Compile Source Code
      run: |
            meson compile -C builddir
    - name: Test Project Code
      run: |
            meson test -C builddir -v
      continue-on-error: true # Mark this step to continue even if it fails
