#
# under: devops:
# author: Michael Gene Brockus (Dreamer)
# gmail: <michaelbrockus@gmail.com>
#
name: XUnit CLI Usage CI

#
# We have is configured so that ci_runner_linux only runs
# when source files, build scripts and this CI files is
# changed, we should not just run CI for all changes.
#
on:
  push:
    paths:
      - "**.c"
      - "**.build"
  pull_request:
    branches:
      - "main"
      - "next"
    paths:
      - "**.c"
      - "**.build"

permissions:
  contents: read

#
# Testing minimum and beta builds of Meson build
# 
jobs:

  run_help:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build System
      run: |
          pip install meson ninja
          sudo apt-get install -y gcc
    - name: Setup Build Directory
      run: |
            meson setup builddir -Dwith_tests=enabled
    - name: Compile Source Code
      run: |
            meson compile -C builddir
    - name: Test Project Code
      run: |
            meson test -C builddir -v --test-args=--help
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Latest_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  run_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build System
      run: |
          pip install meson ninja
          sudo apt-get install -y gcc
    - name: Setup Build Directory
      run: |
            meson setup builddir -Dwith_tests=enabled
    - name: Compile Source Code
      run: |
            meson compile -C builddir
    - name: Test Project Code
      run: |
            meson test -C builddir -v --test-args=--version
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Latest_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  run_verbose:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build System
      run: |
          pip install meson ninja
          sudo apt-get install -y gcc
    - name: Setup Build Directory
      run: |
            meson setup builddir -Dwith_tests=enabled
    - name: Compile Source Code
      run: |
            meson compile -C builddir
    - name: Test Project Code
      run: |
            meson test -C builddir -v --test-args=--verbose
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Latest_Meson_Testlog
        path: builddir/meson-logs/testlog.txt


  run_color:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build System
      run: |
          pip install meson ninja
          sudo apt-get install -y gcc
    - name: Setup Build Directory
      run: |
            meson setup builddir -Dwith_tests=enabled
    - name: Compile Source Code
      run: |
            meson compile -C builddir
    - name: Test Project Code
      run: |
            meson test -C builddir -v --test-args=--color
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Latest_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  run_verbose_and_color:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build System
      run: |
          pip install meson ninja
          sudo apt-get install -y gcc
    - name: Setup Build Directory
      run: |
            meson setup builddir -Dwith_tests=enabled
    - name: Compile Source Code
      run: |
            meson compile -C builddir
    - name: Test Project Code
      run: |
            meson test -C builddir -v --test-args='--verbose —-color'
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Latest_Meson_Testlog
        path: builddir/meson-logs/testlog.txt
